---
- name: Adding Brightbox PPA for Ruby
  apt_repository: repo='ppa:brightbox/ruby-ng'
  when: ansible_distribution == 'Ubuntu'

- name: Install Packages
  action: apt pkg={{item}}
  with_items:
  - ruby{{ruby_version}}
  - ruby{{ruby_version}}-dev
  - build-essential
  - apache2-mpm-worker
  - apache2-dev
  - libssl-dev
  - libcurl4-openssl-dev
  - libapr1-dev
  - libaprutil1-dev

- name: Set default ruby
  command: update-alternatives --install /usr/bin/{{item}} {{item}} /usr/bin/{{item}}{{ruby_version}} 100
  when: ansible_distribution == 'Debian'
  args:
    creates: /usr/bin/{{item}}
  with_items:
  - ruby
  - erb
  - gem
  - irb
  - rake
  - rdoc
  - ri
  - testrb

- name: Install passenger gem
  gem: name=passenger user_install=no version={{passenger_version}}

- name: Run passenger-install-apache2-module
  command: "{{passenger_root}}/bin/passenger-install-apache2-module --auto"
  args:
    creates: "{{passenger_module}}"

- stat: path={{passenger_module}}
  register: passenger_so

- fail: msg="{{passenger_module}} missing"
  when: passenger_so.stat.exists == false

- name: Upload Passenger configuration
  template: src={{item}}.j2 dest=/etc/apache2/mods-available/{{item}}
  with_items:
  - passenger.conf
  - passenger.load
  notify: restart apache2

- name: Enable passenger
  apache2_module: state=present name=passenger
