---
- name: Include phusion repository
  include: repository.yml
  when: ansible_distribution_version != "16.04"

- name: Install Packages
  apt: name={{item}}
  with_items:
  - ruby{{ruby_version}}
  - ruby{{ruby_version}}-dev
  - build-essential
  - apache2
  - apache2-dev
  - libssl-dev
  - libcurl4-openssl-dev
  - libapr1-dev
  - libaprutil1-dev
  - ca-certificates

- name: Set default ruby
  command: update-alternatives --install /usr/bin/{{item}} {{item}} /usr/bin/{{item}}{{ruby_version}} 100
  when: ansible_distribution == 'Debian'
  args:
    creates: /usr/bin/{{item}}
  with_items:
  - ruby
  - erb
  - gem
  - irb
  - rake
  - rdoc
  - ri
  - testrb

- name: Install passenger
  apt: name=libapache2-mod-passenger

- name: Upload Passenger configuration
  template: src={{item}}.j2 dest=/etc/apache2/mods-available/{{item}}
  with_items:
  - passenger.conf
  - passenger.load
  notify: restart apache2

- name: Enable passenger
  apache2_module: state=present name=passenger
